export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "Gracie Sold Store",
  title: "Gracie Sold Store",
  description: "Generated by Gracie's Cuisine",
  links: { github: "https://github.com/sadmann7/shadcn-table-v2" },
  mainNav: [
    {
      title: "Menu",
      href: "/menu",
    },
    {
      title: "Home",
      href: "/",
    },
  ],
};
